In [1]:
from pfns.model.transformer import TableTransformer

model = TableTransformer(
    encoder=None,
    ninp=128,
    nhead=4,
    nhid=128 * 4,
    nlayers=10,
    y_encoder=None,
    style_encoder=lambda x: x.repeat(1, 128),
    y_style_encoder=lambda x: x.repeat(1, 128),
    zero_init=False,
)

Using linear x encoder, as no encoder was provided.
Using linear y encoder, as no y_encoder was provided.


In [2]:
import torch

# Setup a simple toy dataset with 2 datasets, 10 training examples, 1 test example and 1 feature

f = 1

x = torch.randn(2, 11, f)
y = torch.randn(2, 10, f)
x_style = torch.randn(2, f)
y_style = torch.randn(2, 1)

### No Style

In [3]:
model(x, y)


tensor([[[-0.2301]],

        [[-0.0484]]], grad_fn=<ViewBackward0>)

In [4]:
# test last input has effect

x_copy = x.clone()
x_copy[:, 9] = 10.

model(x_copy, y)

tensor([[[-0.2449]],

        [[-0.0415]]], grad_fn=<ViewBackward0>)

In [5]:
# test first input has effect

x_copy = x.clone()
x_copy[:, 0] = 10.

model(x_copy, y, style=x_style)

tensor([[[-0.2767]],

        [[-0.0634]]], grad_fn=<ViewBackward0>)

### X Style

In [6]:
model(x, y, style=x_style)

tensor([[[-0.2641]],

        [[-0.0745]]], grad_fn=<ViewBackward0>)

In [7]:
# test last input has effect

x_copy = x.clone()
x_copy[:, 10] = 10.

model(x_copy, y, style=x_style)

tensor([[[-0.0059]],

        [[ 0.0705]]], grad_fn=<ViewBackward0>)

In [8]:
# test first input has effect

x_copy = x.clone()
x_copy[:, 0] = 10.

model(x_copy, y, style=x_style)

tensor([[[-0.2767]],

        [[-0.0634]]], grad_fn=<ViewBackward0>)

### Y Style

In [9]:
model(x, y, y_style=y_style)

tensor([[[-0.1548]],

        [[-0.0722]]], grad_fn=<ViewBackward0>)

In [10]:
# test last input has effect

x_copy = x.clone()
x_copy[:, 10] = 10.

model(x_copy, y, y_style=y_style)

tensor([[[0.0463]],

        [[0.0736]]], grad_fn=<ViewBackward0>)

In [11]:
# test first input has effect

x_copy = x.clone()
x_copy[:, 0] = 10.

model(x_copy, y, y_style=y_style)

tensor([[[-0.1707]],

        [[-0.0615]]], grad_fn=<ViewBackward0>)

### Both Styles

In [12]:
model(x, y, style=x_style, y_style=y_style)

tensor([[[-0.2002]],

        [[-0.0743]]], grad_fn=<ViewBackward0>)

In [13]:
# test last input has effect

x_copy = x.clone()
x_copy[:, 10] = 10.

model(x_copy, y, style=x_style, y_style=y_style)

tensor([[[0.0187]],

        [[0.0713]]], grad_fn=<ViewBackward0>)

In [14]:
# test first input has effect

x_copy = x.clone()
x_copy[:, 0] = 10.

model(x_copy, y, style=x_style, y_style=y_style)

tensor([[[-0.2164]],

        [[-0.0636]]], grad_fn=<ViewBackward0>)